

groupSizeLimit: 
  maxOfficialGroupSize: 20000
 
dbSetup:
  host: localhost
  port: 3306
  user: root
  password: root
  database: switchboard
  charset: utf8mb4
  timezone: utc
  waitForConnections: true